import { db } from "@workspace/db";
import { siteSettingsTable } from "@workspace/db";
import { logger } from "./logger";

const DEFAULT_SETTINGS = [
  { key: "hero_badge", value: "Female-Led · Black Business Ecosystem · Built for Founders", label: "Hero Badge Text", description: "Short badge in the hero section of the homepage", type: "text" },
  { key: "stat_1_value", value: "$20M+", label: "Stat 1 — Value", description: "First homepage stat value", type: "text" },
  { key: "stat_1_label", value: "Combined revenue generated by Nobellum startups", label: "Stat 1 — Label", description: "First homepage stat description", type: "text" },
  { key: "stat_2_label", value: "Founders in the Nobellum community", label: "Stat 2 — Label", description: "Label for the live founder count stat", type: "text" },
  { key: "stat_3_value", value: "100+", label: "Stat 3 — Value", description: "Third homepage stat value", type: "text" },
  { key: "stat_3_label", value: "Black-owned STEM businesses launched", label: "Stat 3 — Label", description: "Third homepage stat description", type: "text" },
  {
    key: "legal_privacy",
    value: `Nobellum is committed to protecting your privacy. This policy explains how we collect, use, and protect your personal data.

## Information We Collect
We collect information you provide when registering, applying to programs, or using our platform — including your name, email address, company information, and application materials.

## How We Use Your Information
Your data is used to process applications, communicate program updates, and improve our platform. We do not sell your information to third parties.

## Data Security
All sensitive information is encrypted in transit and at rest using industry-standard measures. Access to your data is restricted to authorized Nobellum staff only.

## Your Rights
You may request access to, correction of, or deletion of your personal data at any time by contacting us.

## Contact
For privacy concerns, contact: privacy@nobellum.com`,
    label: "Privacy Policy",
    description: "Privacy policy page content (Markdown supported)",
    type: "markdown",
  },
  {
    key: "legal_terms",
    value: `By using Nobellum Programs, you agree to the following terms of service.

## Eligibility
You must be 18 years or older and legally eligible to participate in our programs to create an account on this platform.

## User Accounts
You are responsible for maintaining the security of your account credentials. Notify us immediately of any unauthorized access at hello@nobellum.com.

## Program Participation
Acceptance into any Nobellum program is at the sole discretion of our selection committee. Admission criteria and deadlines are set per cohort and program.

## Intellectual Property
Content you submit remains yours. By submitting, you grant Nobellum a limited, non-exclusive license to review your materials with our selection committee and advisors.

## Limitation of Liability
Nobellum is not liable for indirect, incidental, or consequential damages arising from platform use.

## Contact
For legal questions, contact: legal@nobellum.com`,
    label: "Terms of Service",
    description: "Terms of service page content (Markdown supported)",
    type: "markdown",
  },
  {
    key: "legal_cookies",
    value: `Nobellum Programs uses cookies to improve your experience on our platform.

## What Are Cookies
Cookies are small text files stored on your device that help us remember your preferences and keep you securely signed in.

## Cookies We Use
- **Essential cookies**: Required for the platform to function — authentication tokens, session management
- **Preference cookies**: Remember your settings such as dark/light mode preferences
- **Analytics cookies**: Help us understand how founders use the platform so we can improve it

## Managing Cookies
You can control and delete cookies through your browser settings. Disabling essential cookies will affect your ability to sign in and use the platform.

## Contact
For cookie-related questions, contact: privacy@nobellum.com`,
    label: "Cookie Policy",
    description: "Cookie policy page content (Markdown supported)",
    type: "markdown",
  },
];

export async function seedDefaultSettings(): Promise<void> {
  try {
    for (const setting of DEFAULT_SETTINGS) {
      await db
        .insert(siteSettingsTable)
        .values(setting)
        .onConflictDoNothing();
    }
    logger.info("Default site settings seeded");
  } catch (err) {
    logger.warn({ err }, "Could not seed default settings (table may not exist yet)");
  }
}
