import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import authRouter from "./auth";
import programsRouter from "./programs";
import configRouter from "./config";
import scoresRouter from "./scores";
import committeeRouter from "./committee";
import exportRouter from "./export";
import adminRouter from "./admin";
import publicApiRouter from "./public-api";
import adminExtrasRouter from "./admin-extras";
import founderExtrasRouter from "./founder-extras";
import founderApplicationsRouter from "./founder-applications";
import uploadRouter from "./upload";
import adminCurriculumRouter from "./admin-curriculum";
import founderCoursesRouter from "./founder-courses";
import founderTractionRouter from "./founder-traction";
import adminTractionRouter from "./admin-traction";
import venturesRouter from "./ventures";
import adminUsersRouter from "./admin-users";
import founderDataroomRouter from "./founder-dataroom";
import founderQaRouter from "./founder-qa";
import founderAdvisoryRouter from "./founder-advisory";
import icRouter from "./ic";
import lpRouter from "./lp";
import mpRouter from "./mp";
import capitalCallsRouter from "./capital-calls";
import capTableRouter from "./cap-table";
import icMeetingsRouter from "./ic-meetings";
import termSheetsRouter from "./term-sheets";
import diligenceRouter from "./diligence";
import founderAsksRouter from "./founder-asks";
import fundsRouter from "./funds";
import lpPortalRouter from "./lp-portal";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use("/auth", authRouter);
router.use(programsRouter);
router.use(configRouter);
router.use(scoresRouter);
router.use(committeeRouter);
router.use(exportRouter);
router.use(adminRouter);
router.use(publicApiRouter);
router.use(adminExtrasRouter);
router.use(founderExtrasRouter);
router.use(founderApplicationsRouter);
router.use(uploadRouter);
router.use(adminCurriculumRouter);
router.use(founderCoursesRouter);
router.use(founderTractionRouter);
router.use(adminTractionRouter);
router.use(venturesRouter);
router.use(adminUsersRouter);
router.use(founderDataroomRouter);
router.use(founderQaRouter);
router.use(founderAdvisoryRouter);
router.use(icRouter);
router.use(lpRouter);
router.use(mpRouter);
router.use(capitalCallsRouter);
router.use(capTableRouter);
router.use(icMeetingsRouter);
router.use(termSheetsRouter);
router.use(diligenceRouter);
router.use(founderAsksRouter);
router.use(fundsRouter);
router.use(lpPortalRouter);

export default router;
