/**
 * Public API routes — no authentication required
 * - GET /api/public/stats       — homepage stats (founder count from DB + admin-configured)
 * - GET /api/public/settings    — all site settings (for homepage metrics, legal etc.)
 * - GET /api/public/testimonials — active testimonials for homepage display
 */
import { Router } from "express";
import { db } from "@workspace/db";
import { foundersTable, siteSettingsTable, testimonialsTable, foundersTable as f } from "@workspace/db";
import { eq, count } from "drizzle-orm";
import { usersTable } from "@workspace/db";

const router = Router();

// GET /api/public/stats
router.get("/public/stats", async (_req, res) => {
  try {
    const [founderCountResult] = await db.select({ count: count() }).from(foundersTable);
    const founderCount = founderCountResult?.count ?? 0;

    const settings = await db.select().from(siteSettingsTable);
    const settingsMap: Record<string, string> = {};
    settings.forEach(s => { settingsMap[s.key] = s.value; });

    res.json({
      founderCount,
      stat1Value: settingsMap["stat_1_value"] ?? "$20M+",
      stat1Label: settingsMap["stat_1_label"] ?? "Combined revenue generated by Nobellum startups",
      stat2Label: settingsMap["stat_2_label"] ?? "Founders in the Nobellum community",
      stat3Value: settingsMap["stat_3_value"] ?? "100+",
      stat3Label: settingsMap["stat_3_label"] ?? "Black-owned STEM businesses launched",
      heroBadge: settingsMap["hero_badge"] ?? "Female-Led · Black Business Ecosystem · Built for Founders",
    });
  } catch (err) {
    res.status(500).json({ error: "Failed to load stats" });
  }
});

// GET /api/public/settings
router.get("/public/settings", async (_req, res) => {
  try {
    const settings = await db.select().from(siteSettingsTable);
    const map: Record<string, string> = {};
    settings.forEach(s => { map[s.key] = s.value; });
    res.json(map);
  } catch (err) {
    res.status(500).json({ error: "Failed to load settings" });
  }
});

// GET /api/public/testimonials
router.get("/public/testimonials", async (_req, res) => {
  try {
    const testimonials = await db
      .select({
        id: testimonialsTable.id,
        content: testimonialsTable.content,
        programName: testimonialsTable.programName,
        cohortYear: testimonialsTable.cohortYear,
        displayOrder: testimonialsTable.displayOrder,
        founderName: usersTable.name,
        founderAvatar: foundersTable.avatarUrl,
        founderCompany: foundersTable.companyName,
        founderCity: foundersTable.city,
        founderCountry: foundersTable.country,
        founderSector: foundersTable.sector,
      })
      .from(testimonialsTable)
      .innerJoin(foundersTable, eq(testimonialsTable.founderId, foundersTable.id))
      .innerJoin(usersTable, eq(foundersTable.userId, usersTable.id))
      .where(eq(testimonialsTable.isActive, true))
      .orderBy(testimonialsTable.displayOrder);

    res.json(testimonials);
  } catch (err) {
    res.status(500).json({ error: "Failed to load testimonials" });
  }
});

export default router;
