import { useState, useEffect, useCallback } from "react";
import { useLocation } from "wouter";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { useTheme } from "@/lib/theme";
import {
  ArrowRight,
  Sun,
  Moon,
  Menu,
  X,
  Users,
  BarChart3,
  Shield,
  Globe,
  Star,
  ChevronDown,
  Rocket,
  Building2,
  Trophy,
  FileText,
  MessageSquare,
  Database,
  CheckCircle2,
  ArrowUpRight,
  Sparkles,
  TrendingUp,
  Clock,
  Award,
  Heart,
  Zap,
  MapPin,
  ExternalLink,
} from "lucide-react";

const BASE = import.meta.env.BASE_URL.replace(/\/$/, "");

type SiteStats = {
  founderCount: number;
  stat1Value: string;
  stat1Label: string;
  stat2Label: string;
  stat3Value: string;
  stat3Label: string;
  heroBadge: string;
};

const DEFAULT_STATS: SiteStats = {
  founderCount: 0,
  stat1Value: "$20M+",
  stat1Label: "Combined revenue generated by Startling Capital startups",
  stat2Label: "Founders in the startling-capital.community",
  stat3Value: "100+",
  stat3Label: "Black-owned STEM businesses launched",
  heroBadge: "Female-Led · Black Business Ecosystem · Built for Founders",
};

function useSiteStats() {
  const [stats, setStats] = useState<SiteStats>(DEFAULT_STATS);
  useEffect(() => {
    fetch(`${BASE}/api/public/stats`)
      .then(r => r.ok ? r.json() : null)
      .then(data => { if (data) setStats(data); })
      .catch(() => {});
  }, []);
  return stats;
}

type PublicTestimonial = {
  id: number;
  content: string;
  programName: string | null;
  cohortYear: string | null;
  displayOrder: number;
  founderName: string;
  founderAvatar: string | null;
  founderCompany: string | null;
  founderCity: string | null;
  founderCountry: string | null;
  founderSector: string | null;
};

function usePublicTestimonials() {
  const [testimonials, setTestimonials] = useState<PublicTestimonial[]>([]);
  useEffect(() => {
    fetch(`${BASE}/api/public/testimonials`)
      .then(r => r.ok ? r.json() : [])
      .then(setTestimonials)
      .catch(() => {});
  }, []);
  return testimonials;
}

const WELCOME_MESSAGES = [
  "Empowering Black innovators to launch and scale sustainable ventures.",
  "The global accelerator you've been waiting for — based in Canada, reaching the world.",
  "From idea to investment-ready. Your journey starts here.",
  "Startling Capital is not just an accelerator. We are a transformative force.",
  "Join 5,000+ community members driving economic impact through entrepreneurship.",
];

const PARTNERS = [
  "RBC", "BMO", "The Bridge", "The Hub", "City of Toronto", "Ecosystem Partner"
];

function NavBar() {
  const [, navigate] = useLocation();
  const { resolvedTheme, toggleTheme } = useTheme();
  const [mobileOpen, setMobileOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 20);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  return (
    <nav className={`fixed top-0 left-0 right-0 z-50 transition-all duration-300 ${
      scrolled
        ? "bg-background/95 backdrop-blur-md border-b border-border shadow-sm"
        : "bg-transparent"
    }`}>
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex items-center justify-between h-16">
          <div className="flex items-center gap-2.5 cursor-pointer" onClick={() => navigate("/")}>
            <div className="w-8 h-8 rounded-lg gradient-teal flex items-center justify-center">
              <span className="text-white font-bold text-sm font-display">S</span>
            </div>
            <div>
              <span className="font-display font-bold text-base tracking-tight text-foreground leading-none">Startling Capital</span>
              <div className="text-[10px] text-muted-foreground leading-none font-medium tracking-wide">PROGRAMS</div>
            </div>
          </div>

          <div className="hidden md:flex items-center gap-8">
            <a href="#programs" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Programs</a>
            <a href="#how-it-works" className="text-sm text-muted-foreground hover:text-foreground transition-colors">How It Works</a>
            <a href="#our-mission" className="text-sm text-muted-foreground hover:text-foreground transition-colors">Our Mission</a>
            <a href="#faq" className="text-sm text-muted-foreground hover:text-foreground transition-colors">FAQ</a>
          </div>

          <div className="flex items-center gap-3">
            <button
              onClick={toggleTheme}
              className="w-9 h-9 rounded-lg flex items-center justify-center text-muted-foreground hover:text-foreground hover:bg-secondary transition-all"
              aria-label="Toggle theme"
            >
              {resolvedTheme === "dark" ? <Sun className="h-4 w-4" /> : <Moon className="h-4 w-4" />}
            </button>
            <Button variant="ghost" size="sm" onClick={() => navigate("/login")}>Sign In</Button>
            <Button size="sm" className="gradient-teal text-white border-0 hover:opacity-90 transition-opacity hidden sm:flex" onClick={() => navigate("/register")}>
              Apply Now <ArrowRight className="ml-1.5 h-3.5 w-3.5" />
            </Button>
            <button
              className="md:hidden w-9 h-9 rounded-lg flex items-center justify-center text-muted-foreground hover:bg-secondary"
              onClick={() => setMobileOpen(!mobileOpen)}
            >
              {mobileOpen ? <X className="h-4 w-4" /> : <Menu className="h-4 w-4" />}
            </button>
          </div>
        </div>
      </div>

      {mobileOpen && (
        <div className="md:hidden bg-background/98 backdrop-blur-md border-b border-border">
          <div className="px-4 py-4 space-y-3">
            <a href="#programs" className="block text-sm py-2 text-muted-foreground" onClick={() => setMobileOpen(false)}>Programs</a>
            <a href="#how-it-works" className="block text-sm py-2 text-muted-foreground" onClick={() => setMobileOpen(false)}>How It Works</a>
            <a href="#our-mission" className="block text-sm py-2 text-muted-foreground" onClick={() => setMobileOpen(false)}>Our Mission</a>
            <a href="#faq" className="block text-sm py-2 text-muted-foreground" onClick={() => setMobileOpen(false)}>FAQ</a>
            <Button className="w-full gradient-teal text-white border-0" onClick={() => navigate("/register")}>Apply Now</Button>
          </div>
        </div>
      )}
    </nav>
  );
}

function HeroSection() {
  const [, navigate] = useLocation();
  const [messageIndex, setMessageIndex] = useState(0);
  const [displayText, setDisplayText] = useState("");
  const [isDeleting, setIsDeleting] = useState(false);
  const stats = useSiteStats();

  useEffect(() => {
    const fullText = WELCOME_MESSAGES[messageIndex];
    let timeout: ReturnType<typeof setTimeout>;

    if (!isDeleting && displayText === fullText) {
      timeout = setTimeout(() => setIsDeleting(true), 3200);
    } else if (isDeleting && displayText === "") {
      setIsDeleting(false);
      setMessageIndex((i) => (i + 1) % WELCOME_MESSAGES.length);
    } else {
      const speed = isDeleting ? 22 : 42;
      timeout = setTimeout(() => {
        setDisplayText(isDeleting ? fullText.slice(0, displayText.length - 1) : fullText.slice(0, displayText.length + 1));
      }, speed);
    }
    return () => clearTimeout(timeout);
  }, [displayText, isDeleting, messageIndex]);

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden pt-16">
      <div className="absolute inset-0 hero-grid" />
      <div className="absolute inset-0 bg-gradient-to-b from-transparent via-background/60 to-background" />
      <div className="absolute top-1/4 -left-32 w-96 h-96 bg-primary/8 rounded-full blur-3xl animate-float" />
      <div className="absolute bottom-1/4 -right-32 w-96 h-96 bg-blue-500/6 rounded-full blur-3xl animate-float-delayed" />

      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <div className="animate-fade-in-up mb-6 inline-flex items-center gap-3">
          <Badge className="bg-primary/10 text-primary border-primary/20 px-4 py-1.5 text-sm gap-2">
            <Sparkles className="h-3.5 w-3.5" />
            {stats.heroBadge}
          </Badge>
        </div>

        <h1 className="animate-fade-in-up-delay-1 font-display font-bold text-5xl sm:text-6xl md:text-7xl lg:text-8xl text-foreground leading-[1.05] tracking-tight mb-4">
          The Global{" "}
          <span className="text-gradient">Accelerator</span>
          <br />
          You've Been{" "}
          <span className="text-gradient">Waiting For</span>
        </h1>

        <div className="animate-fade-in-up-delay-2 h-20 sm:h-12 flex items-center justify-center mb-8">
          <p className="text-base sm:text-lg text-muted-foreground max-w-2xl font-medium leading-relaxed">
            {displayText}
            <span className="inline-block w-0.5 h-5 ml-0.5 bg-primary align-middle animate-pulse" />
          </p>
        </div>

        <div className="animate-fade-in-up-delay-3 flex flex-col sm:flex-row gap-4 justify-center items-center mb-16">
          <Button
            size="lg"
            className="gradient-teal text-white border-0 hover:opacity-90 transition-all text-base px-8 py-6 rounded-xl animate-pulse-glow"
            onClick={() => navigate("/register")}
          >
            <Rocket className="mr-2 h-5 w-5" />
            Apply to a Program
          </Button>
          <Button
            variant="outline"
            size="lg"
            className="text-base px-8 py-6 rounded-xl gap-2 border-border hover:bg-secondary"
            onClick={() => document.getElementById("programs")?.scrollIntoView({ behavior: "smooth" })}
          >
            <Sparkles className="h-4 w-4" />
            Explore Programs
          </Button>
        </div>

        {/* Stats */}
        <div className="animate-fade-in-up-delay-4 grid grid-cols-2 sm:grid-cols-3 gap-4 max-w-2xl mx-auto mb-10">
          {[
            { value: stats.stat1Value, label: stats.stat1Label, icon: TrendingUp },
            { value: stats.founderCount > 0 ? `${stats.founderCount.toLocaleString()}+` : "—", label: stats.stat2Label, icon: Users },
            { value: stats.stat3Value, label: stats.stat3Label, icon: Trophy },
          ].map((stat) => (
            <div key={stat.label} className="glass rounded-2xl p-4 text-center card-hover sm:last:col-span-1 last:col-span-2 sm:last:col-auto">
              <stat.icon className="h-5 w-5 text-primary mx-auto mb-2" />
              <div className="font-display font-bold text-2xl text-foreground">{stat.value}</div>
              <div className="text-xs text-muted-foreground mt-1 leading-snug">{stat.label}</div>
            </div>
          ))}
        </div>

        {/* Partners marquee */}
        <div className="animate-fade-in-up-delay-4 border-t border-border pt-8">
          <p className="text-xs text-muted-foreground uppercase tracking-widest mb-4 font-medium">Trusted ecosystem partners</p>
          <div className="flex items-center justify-center flex-wrap gap-6">
            {["RBC", "BMO", "The Bridge", "The Hub", "City of Toronto", "Scarborough"].map((partner) => (
              <div key={partner} className="bg-secondary/60 rounded-lg px-4 py-2 text-xs font-semibold text-muted-foreground">
                {partner}
              </div>
            ))}
          </div>
        </div>

        <div className="mt-12 flex justify-center animate-bounce">
          <a href="#programs" className="text-muted-foreground hover:text-foreground transition-colors">
            <ChevronDown className="h-6 w-6" />
          </a>
        </div>
      </div>
    </section>
  );
}

function MissionSection() {
  return (
    <section id="our-mission" className="py-24 bg-secondary/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="grid lg:grid-cols-2 gap-16 items-center">
          <div>
            <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">Who We Are</Badge>
            <h2 className="font-display font-bold text-4xl sm:text-5xl text-foreground mb-6 leading-tight">
              A Transformative Force for{" "}
              <span className="text-gradient">Black Innovation</span>
            </h2>
            <p className="text-muted-foreground text-lg mb-6 leading-relaxed">
              <strong className="text-foreground">Startling Capital</strong> is a female-led social and technology enterprise dedicated to empowering the Black business ecosystem. With a mission to support Black innovators in launching and scaling sustainable ventures, Startling Capital is committed to inspiring change and driving economic impact through entrepreneurship.
            </p>
            <p className="text-muted-foreground leading-relaxed mb-8">
              Having surpassed our 5-year mandate of launching 100 Black-owned STEM businesses, we are now scaling ventures into sustainable, high-impact enterprises. Our best-in-class framework equips underrepresented founders with cutting-edge tools, funding access, strategic partnerships, and a community-driven ecosystem.
            </p>
            <div className="grid grid-cols-2 gap-3">
              {[
                { icon: CheckCircle2, text: "Become investment-ready" },
                { icon: CheckCircle2, text: "Coaching with Executives in Residence" },
                { icon: CheckCircle2, text: "Expand your network globally" },
                { icon: CheckCircle2, text: "Real-time IP resources" },
              ].map((item) => (
                <div key={item.text} className="flex items-start gap-2">
                  <item.icon className="h-4 w-4 text-primary mt-0.5 shrink-0" />
                  <span className="text-sm text-muted-foreground">{item.text}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="grid grid-cols-2 gap-4">
            {[
              { value: "$20M+", label: "Combined revenue generated by Startling Capital startups", color: "from-teal-500/20 to-cyan-500/20", border: "border-teal-500/20" },
              { value: "5,000+", label: "Members in the startling-capital.community", color: "from-purple-500/20 to-pink-500/20", border: "border-purple-500/20" },
              { value: "$550M+", label: "Combined funds of VC investors in our network", color: "from-blue-500/20 to-indigo-500/20", border: "border-blue-500/20" },
              { value: "100+", label: "Black-owned STEM businesses launched", color: "from-orange-500/20 to-yellow-500/20", border: "border-orange-500/20" },
            ].map((stat) => (
              <div key={stat.label} className={`bg-gradient-to-br ${stat.color} border ${stat.border} rounded-2xl p-6 card-hover`}>
                <div className="font-display font-bold text-3xl text-foreground mb-2">{stat.value}</div>
                <p className="text-xs text-muted-foreground leading-relaxed">{stat.label}</p>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
}

function ProgramsSection() {
  const [, navigate] = useLocation();

  const programs = [
    {
      id: "innovator",
      name: "Innovator Program",
      badge: "Applications Open",
      badgeColor: "bg-teal-500/10 text-teal-700 dark:text-teal-400 border-teal-500/20",
      description: "Our flagship accelerator for Black entrepreneurs ready to launch and scale. Access tailored mentorship, resources, and connections to turn your innovative ideas into successful ventures.",
      duration: "12 weeks",
      format: "Hybrid",
      location: "Toronto, Canada",
      spots: "20 spots",
      deadline: "Rolling admissions",
      tags: ["STEM", "Tech", "All Sectors", "Early Stage"],
      benefits: ["Executive mentorship", "IP resources", "Investor network", "Pitch coaching"],
      gradient: "from-teal-500 to-cyan-500",
      url: "https://www.startling-capital.com/program",
    },
    {
      id: "wise",
      name: "WISE Women",
      badge: "Now Accepting",
      badgeColor: "bg-purple-500/10 text-purple-700 dark:text-purple-400 border-purple-500/20",
      description: "Women Innovating for Sustainable Enterprise — a dedicated accelerator empowering Black women founders with resources, coaching, and strategic connections to scale their ventures.",
      duration: "8 weeks",
      format: "Hybrid",
      location: "Toronto + Virtual",
      spots: "15 spots",
      deadline: "Rolling admissions",
      tags: ["Women-Led", "Social Impact", "STEM", "All Sectors"],
      benefits: ["Women-focused mentorship", "Community network", "Business coaching", "Peer learning"],
      gradient: "from-purple-500 to-pink-500",
      url: "https://www.startling-capital.com/wise",
    },
    {
      id: "cei-global",
      name: "CEI Global",
      badge: "International",
      badgeColor: "bg-blue-500/10 text-blue-700 dark:text-blue-400 border-blue-500/20",
      description: "Our global accelerator program connecting Black innovators across the diaspora with international markets, investors, and a worldwide community of changemakers.",
      duration: "16 weeks",
      format: "Virtual + In-Person",
      location: "Global",
      spots: "10 spots",
      deadline: "Rolling admissions",
      tags: ["Global", "Diaspora", "Scale-up", "International"],
      benefits: ["Global market access", "International partnerships", "Cross-border mentorship", "Investment readiness"],
      gradient: "from-blue-500 to-indigo-500",
      url: "https://www.startling-capital.com/global",
    },
  ];

  return (
    <section id="programs" className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <div className="text-center mb-16">
        <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">Our Programs</Badge>
        <h2 className="font-display font-bold text-4xl sm:text-5xl text-foreground mb-4">
          Find Your{" "}
          <span className="text-gradient">Program</span>
        </h2>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
          Three transformative programs designed for different stages, sectors, and communities of Black innovators — from first idea to global scale.
        </p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {programs.map((program, i) => (
          <div
            key={program.id}
            className="relative rounded-2xl border border-border bg-card overflow-hidden card-hover group cursor-pointer flex flex-col"
            style={{ animationDelay: `${i * 0.1}s` }}
            onClick={() => navigate("/register")}
          >
            <div className={`h-1.5 bg-gradient-to-r ${program.gradient}`} />

            <div className="p-6 flex flex-col flex-1">
              <div className="flex items-start justify-between gap-2 mb-4">
                <Badge className={`text-xs font-medium ${program.badgeColor} border`}>
                  {program.badge}
                </Badge>
                <a
                  href={program.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-muted-foreground hover:text-primary transition-colors"
                  onClick={(e) => e.stopPropagation()}
                >
                  <ExternalLink className="h-3.5 w-3.5" />
                </a>
              </div>

              <h3 className="font-display font-bold text-2xl text-foreground mb-2 group-hover:text-primary transition-colors">
                {program.name}
              </h3>
              <p className="text-muted-foreground text-sm leading-relaxed mb-5 flex-1">
                {program.description}
              </p>

              <div className="grid grid-cols-2 gap-2 mb-5">
                {[
                  { label: "Duration", value: program.duration, icon: Clock },
                  { label: "Format", value: program.format, icon: Globe },
                  { label: "Location", value: program.location, icon: MapPin },
                  { label: "Spots", value: program.spots, icon: Users },
                ].map((detail) => (
                  <div key={detail.label} className="bg-secondary/60 rounded-xl p-2.5">
                    <detail.icon className="h-3 w-3 text-primary mb-1" />
                    <div className="text-[10px] text-muted-foreground">{detail.label}</div>
                    <div className="text-xs font-semibold text-foreground leading-tight">{detail.value}</div>
                  </div>
                ))}
              </div>

              {/* Benefits */}
              <div className="mb-5">
                <p className="text-xs font-semibold text-foreground mb-2">Key Benefits</p>
                <div className="space-y-1.5">
                  {program.benefits.map((b) => (
                    <div key={b} className="flex items-center gap-2 text-xs text-muted-foreground">
                      <CheckCircle2 className="h-3 w-3 text-primary shrink-0" />
                      {b}
                    </div>
                  ))}
                </div>
              </div>

              <div className="flex flex-wrap gap-1.5 mb-5">
                {program.tags.map((tag) => (
                  <span key={tag} className="text-xs bg-accent text-accent-foreground px-2.5 py-1 rounded-full">
                    {tag}
                  </span>
                ))}
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-border">
                <div>
                  <div className="text-xs text-muted-foreground">Applications</div>
                  <div className="text-sm font-semibold text-foreground">{program.deadline}</div>
                </div>
                <Button size="sm" className="gradient-teal text-white border-0 hover:opacity-90 gap-1.5">
                  Apply <ArrowUpRight className="h-3.5 w-3.5" />
                </Button>
              </div>
            </div>
          </div>
        ))}
      </div>

      <div className="text-center mt-8">
        <p className="text-sm text-muted-foreground">
          Not sure which program is right for you?{" "}
          <a href="https://www.startling-capital.com/about-us-1" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline font-medium inline-flex items-center gap-1">
            Learn more about our Programs & Initiatives <ExternalLink className="h-3 w-3" />
          </a>
        </p>
      </div>
    </section>
  );
}

function HowItWorksSection() {
  const steps = [
    {
      step: "01",
      title: "Create Your Account",
      description: "Register as a founder in under 2 minutes. Your profile becomes your passport to all Startling Capital programs.",
      icon: Users,
      color: "from-teal-500 to-cyan-500",
    },
    {
      step: "02",
      title: "Apply to a Program",
      description: "Browse active programs and submit a tailored application. Our form is designed to highlight what matters — your idea and vision.",
      icon: FileText,
      color: "from-blue-500 to-indigo-500",
    },
    {
      step: "03",
      title: "Get Reviewed & Scored",
      description: "Our expert selection committee evaluates applications using a structured framework. You receive constructive feedback regardless of outcome.",
      icon: Star,
      color: "from-violet-500 to-purple-500",
    },
    {
      step: "04",
      title: "Accelerate & Scale",
      description: "Accepted founders join a cohort with Executive mentors, workshops, IP resources, and investor connections — from Toronto to the world.",
      icon: Rocket,
      color: "from-orange-500 to-rose-500",
    },
  ];

  return (
    <section id="how-it-works" className="py-24 bg-secondary/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">The Process</Badge>
          <h2 className="font-display font-bold text-4xl sm:text-5xl text-foreground mb-4">
            From Application to{" "}
            <span className="text-gradient">Scale</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            A transparent, structured process designed to identify and amplify the most promising Black-owned ventures.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {steps.map((step, i) => (
            <div key={step.step} className="relative">
              <div className="relative z-10 bg-card border border-border rounded-2xl p-6 card-hover text-center">
                <div className={`w-16 h-16 rounded-2xl bg-gradient-to-br ${step.color} flex items-center justify-center mx-auto mb-4`}>
                  <step.icon className="h-7 w-7 text-white" />
                </div>
                <div className="text-4xl font-display font-bold text-border/60 mb-2">{step.step}</div>
                <h3 className="font-display font-bold text-lg text-foreground mb-3">{step.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{step.description}</p>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function ForFoundersSection() {
  const [, navigate] = useLocation();

  const features = [
    {
      icon: Database,
      title: "Investor-Ready Data Room",
      description: "Upload pitch decks, financials, legal docs, and more. Share securely with VCs and strategic partners.",
      badge: null,
    },
    {
      icon: BarChart3,
      title: "Application Tracking",
      description: "Real-time status updates on every application. Know exactly where you stand with detailed feedback.",
      badge: null,
    },
    {
      icon: MessageSquare,
      title: "Email Notifications",
      description: "Automatic email updates at every stage — from submission through to decision. Never miss an update.",
      badge: "New",
    },
    {
      icon: Star,
      title: "Executive Advisory",
      description: "Access curated advisory links, Executive in Residence sessions, and expert resources matched to your stage.",
      badge: null,
    },
    {
      icon: Shield,
      title: "Secure & Private",
      description: "Bank-grade security for all your sensitive business data. You control who sees what, always.",
      badge: null,
    },
    {
      icon: Globe,
      title: "Global Network",
      description: "Connect with a network of founders, VCs, and mentors across Canada, the US, UK, and Africa.",
      badge: null,
    },
  ];

  return (
    <section id="for-founders" className="py-24 px-4 sm:px-6 lg:px-8 max-w-7xl mx-auto">
      <div className="grid lg:grid-cols-2 gap-16 items-center">
        <div>
          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">For Founders</Badge>
          <h2 className="font-display font-bold text-4xl sm:text-5xl text-foreground mb-6 leading-tight">
            Everything you need,{" "}
            <span className="text-gradient">in one place</span>
          </h2>
          <p className="text-muted-foreground text-lg mb-8 leading-relaxed">
            Your founder portal is your command center for managing your entire Startling Capital journey — from first application to investment-ready.
          </p>

          <div className="space-y-3 mb-8">
            {[
              "Automatic email updates at every application stage",
              "Multi-program applications tracked in one place",
              "Investor data room with document organization",
              "Executive in Residence booking and scheduling",
            ].map((point) => (
              <div key={point} className="flex items-center gap-3">
                <div className="w-5 h-5 rounded-full bg-primary/15 flex items-center justify-center shrink-0">
                  <CheckCircle2 className="h-3 w-3 text-primary" />
                </div>
                <span className="text-muted-foreground text-sm">{point}</span>
              </div>
            ))}
          </div>

          <Button size="lg" className="gradient-teal text-white border-0 hover:opacity-90 gap-2" onClick={() => navigate("/register")}>
            Create Your Account <ArrowRight className="h-4 w-4" />
          </Button>
        </div>

        <div className="grid grid-cols-2 gap-4">
          {features.map((feature) => (
            <div key={feature.title} className="bg-card border border-border rounded-2xl p-5 card-hover relative overflow-hidden group">
              {feature.badge && (
                <span className="absolute top-3 right-3 text-[10px] font-bold bg-primary text-primary-foreground px-2 py-0.5 rounded-full">
                  {feature.badge}
                </span>
              )}
              <div className="w-10 h-10 rounded-xl bg-primary/10 flex items-center justify-center mb-3 group-hover:bg-primary/20 transition-colors">
                <feature.icon className="h-5 w-5 text-primary" />
              </div>
              <h3 className="font-display font-semibold text-foreground text-sm mb-2">{feature.title}</h3>
              <p className="text-xs text-muted-foreground leading-relaxed">{feature.description}</p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

const FALLBACK_TESTIMONIALS = [
  {
    id: -1,
    content: "Startling Capital didn't just give me access to resources — they gave me a community. The Executive in Residence mentorship changed how I think about scaling my business.",
    founderName: "Founder, Startling Capital Alumni",
    founderCompany: null,
    founderCity: "Toronto",
    founderCountry: "Canada",
    founderSector: null,
    founderAvatar: null,
    programName: "Innovator Program",
    cohortYear: "2024",
    displayOrder: 0,
  },
  {
    id: -2,
    content: "As a Black woman founder, WISE Women gave me a space where I truly belonged. The network I built has been invaluable to my fundraising journey.",
    founderName: "Woman Founder, Alumni",
    founderCompany: null,
    founderCity: null,
    founderCountry: "Canada",
    founderSector: null,
    founderAvatar: null,
    programName: "WISE Women",
    cohortYear: "2024",
    displayOrder: 1,
  },
  {
    id: -3,
    content: "CEI Global opened doors I didn't know existed. The international connections and cross-border partnerships have transformed our business model completely.",
    founderName: "Global Entrepreneur, Alumni",
    founderCompany: null,
    founderCity: null,
    founderCountry: "Nigeria",
    founderSector: null,
    founderAvatar: null,
    programName: "CEI Global",
    cohortYear: "2023",
    displayOrder: 2,
  },
];

const AVATAR_GRADIENTS = [
  "from-teal-500 to-cyan-500",
  "from-purple-500 to-pink-500",
  "from-blue-500 to-indigo-500",
  "from-orange-500 to-amber-500",
  "from-green-500 to-emerald-500",
];

function TestimonialsSection() {
  const apiTestimonials = usePublicTestimonials();
  const testimonials = apiTestimonials.length > 0 ? apiTestimonials : FALLBACK_TESTIMONIALS;

  const initials = (name: string) => name.split(" ").map(n => n[0]).join("").slice(0, 2).toUpperCase();

  return (
    <section className="py-24 bg-secondary/30">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">Founder Stories</Badge>
          <h2 className="font-display font-bold text-4xl sm:text-5xl text-foreground mb-4">
            Founders who{" "}
            <span className="text-gradient">transformed</span>
          </h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          {testimonials.slice(0, 6).map((t, idx) => (
            <div key={t.id} className="bg-card border border-border rounded-2xl p-6 card-hover flex flex-col">
              <div className="flex mb-4">
                {[...Array(5)].map((_, i) => (
                  <Star key={i} className="h-4 w-4 text-yellow-500 fill-yellow-500" />
                ))}
              </div>
              <blockquote className="text-foreground text-sm leading-relaxed flex-1 mb-6">
                "{t.content}"
              </blockquote>
              <div className="flex items-center gap-3">
                {t.founderAvatar ? (
                  <img src={t.founderAvatar} alt={t.founderName} className="w-10 h-10 rounded-full object-cover shrink-0" />
                ) : (
                  <div className={`w-10 h-10 rounded-full bg-gradient-to-br ${AVATAR_GRADIENTS[idx % AVATAR_GRADIENTS.length]} flex items-center justify-center text-white font-bold text-sm shrink-0`}>
                    {initials(t.founderName)}
                  </div>
                )}
                <div>
                  <div className="font-semibold text-foreground text-sm">{t.founderName}</div>
                  {(t.founderCity || t.founderCountry) && (
                    <div className="text-xs text-muted-foreground">{[t.founderCity, t.founderCountry].filter(Boolean).join(", ")}</div>
                  )}
                  {t.programName && (
                    <div className="text-xs text-primary mt-0.5">{t.programName}{t.cohortYear ? ` · ${t.cohortYear}` : ""}</div>
                  )}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}

function FaqSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);

  const faqs = [
    {
      q: "Who can apply to Startling Capital programs?",
      a: "Startling Capital focuses on Black entrepreneurs and innovators at various stages. Our programs are designed for founders building STEM or tech-enabled businesses, though we support all sectors. Specific eligibility varies by program — WISE Women is exclusively for women founders, while CEI Global serves the international diaspora.",
    },
    {
      q: "Is Startling Capital only based in Canada?",
      a: "Startling Capital is headquartered in Toronto, Canada, but we are proudly global. Our CEI Global program serves entrepreneurs from across the African diaspora worldwide, and our community of 5,000+ members spans North America, the UK, and Africa.",
    },
    {
      q: "Is there a cost to apply or participate?",
      a: "Applications are completely free. Accepted founders join our programs at no cost. Startling Capital's model is built around investing in your success, not charging you to participate.",
    },
    {
      q: "What benefits do program participants receive?",
      a: "Benefits vary by program but include: Executive in Residence mentorship, IP resources and legal guidance, access to our $550M+ VC investor network, pitch coaching and preparation, community membership, business workshops, and ongoing alumni support.",
    },
    {
      q: "What is the data room and why do I need one?",
      a: "Your data room is a secure, organized document vault for key business materials — pitch deck, financials, legal docs, and team bios. When investors in Startling Capital's $550M+ VC network want to evaluate portfolio companies, a well-organized data room dramatically accelerates due diligence.",
    },
    {
      q: "How does Startling Capital Programs (this platform) differ from the main Startling Capital website?",
      a: "Startling Capital Programs is our internal management system for founders who have applied or been accepted into a Startling Capital program. It gives you a personal founder portal, application tracking, data room, and access to resources. The main Startling Capital website (startling-capital.com) provides marketing and general information.",
    },
  ];

  return (
    <section id="faq" className="py-24 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
      <div className="text-center mb-16">
        <Badge className="mb-4 bg-primary/10 text-primary border-primary/20">FAQ</Badge>
        <h2 className="font-display font-bold text-4xl sm:text-5xl text-foreground mb-4">
          Common{" "}
          <span className="text-gradient">Questions</span>
        </h2>
      </div>

      <div className="space-y-3">
        {faqs.map((faq, i) => (
          <div key={i} className="bg-card border border-border rounded-2xl overflow-hidden transition-all duration-200">
            <button
              className="w-full text-left px-6 py-5 flex items-center justify-between gap-4 hover:bg-secondary/50 transition-colors"
              onClick={() => setOpenIndex(openIndex === i ? null : i)}
            >
              <span className="font-semibold text-foreground text-sm">{faq.q}</span>
              <ChevronDown className={`h-4 w-4 text-muted-foreground shrink-0 transition-transform duration-200 ${openIndex === i ? "rotate-180" : ""}`} />
            </button>
            {openIndex === i && (
              <div className="px-6 pb-5 text-sm text-muted-foreground leading-relaxed border-t border-border pt-4">
                {faq.a}
              </div>
            )}
          </div>
        ))}
      </div>
    </section>
  );
}

function CtaBanner() {
  const [, navigate] = useLocation();

  return (
    <section className="py-24 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <div className="relative overflow-hidden rounded-3xl gradient-hero p-12 text-center teal-glow">
          <div className="absolute top-0 right-0 w-64 h-64 bg-white/5 rounded-full -translate-y-1/2 translate-x-1/2" />
          <div className="absolute bottom-0 left-0 w-48 h-48 bg-white/5 rounded-full translate-y-1/2 -translate-x-1/2" />

          <div className="relative">
            <div className="inline-flex items-center gap-2 bg-white/15 text-white rounded-full px-4 py-2 text-sm font-medium mb-6">
              <Heart className="h-4 w-4" />
              Female-led · Black-led · Canada-based · Globally focused
            </div>
            <h2 className="font-display font-bold text-4xl sm:text-5xl text-white mb-4 leading-tight">
              Ready to join the<br />startling-capital.community?
            </h2>
            <p className="text-white/80 text-lg mb-8 max-w-xl mx-auto">
              Join 5,000+ innovators who are building the next generation of high-impact Black-owned businesses.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Button
                size="lg"
                className="bg-white text-primary hover:bg-white/90 font-bold text-base px-8 py-6 rounded-xl gap-2"
                onClick={() => navigate("/register")}
              >
                <Rocket className="h-5 w-5" />
                Apply Today — It's Free
              </Button>
              <Button
                variant="outline"
                size="lg"
                className="border-white/30 text-white hover:bg-white/10 text-base px-8 py-6 rounded-xl gap-2"
                onClick={() => window.open("https://www.startling-capital.com/about-us-1", "_blank")}
              >
                <ExternalLink className="h-4 w-4" />
                Learn More at startling-capital.com
              </Button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}

function Footer() {
  const [, navigate] = useLocation();

  return (
    <footer className="border-t border-border bg-card">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-12">
          <div className="md:col-span-2">
            <div className="flex items-center gap-2.5 mb-4 cursor-pointer" onClick={() => navigate("/")}>
              <div className="w-8 h-8 rounded-lg gradient-teal flex items-center justify-center">
                <span className="text-white font-bold text-sm font-display">N</span>
              </div>
              <div>
                <span className="font-display font-bold text-lg text-foreground leading-none">Startling Capital</span>
                <div className="text-[10px] text-muted-foreground font-medium tracking-wide">PROGRAMS</div>
              </div>
            </div>
            <p className="text-muted-foreground text-sm leading-relaxed max-w-sm mb-3">
              A female-led social and technology enterprise dedicated to empowering the Black business ecosystem. Based in Toronto, Canada — reaching the world.
            </p>
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground mb-4">
              <MapPin className="h-3 w-3" />
              Toronto, Ontario, Canada
            </div>
            <div className="flex gap-3">
              <a href="https://www.startling-capital.com" target="_blank" rel="noopener noreferrer" className="text-xs text-muted-foreground hover:text-foreground transition-colors border border-border rounded-lg px-3 py-1.5 inline-flex items-center gap-1">
                startling-capital.com <ExternalLink className="h-3 w-3" />
              </a>
            </div>
          </div>

          <div>
            <h4 className="font-semibold text-foreground text-sm mb-4">Programs</h4>
            <ul className="space-y-2.5">
              {[
                { label: "Innovator Program", href: "https://www.startling-capital.com/program" },
                { label: "WISE Women", href: "https://www.startling-capital.com/wise" },
                { label: "CEI Global", href: "https://www.startling-capital.com/global" },
                { label: "Apply Now", href: "/register" },
                { label: "Sign In", href: "/login" },
              ].map((link) => (
                <li key={link.label}>
                  <a href={link.href} className="text-sm text-muted-foreground hover:text-foreground transition-colors">
                    {link.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4 className="font-semibold text-foreground text-sm mb-4">Legal</h4>
            <ul className="space-y-2.5">
              {[
                { label: "Privacy Policy", href: "/legal/privacy" },
                { label: "Terms of Service", href: "/legal/terms" },
                { label: "Cookie Policy", href: "/legal/cookies" },
              ].map((item) => (
                <li key={item.label}>
                  <a href={item.href} className="text-sm text-muted-foreground hover:text-foreground transition-colors">{item.label}</a>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="border-t border-border pt-6 flex flex-col sm:flex-row items-center justify-between gap-4">
          <p className="text-xs text-muted-foreground">
            © {new Date().getFullYear()} Startling Capital. All rights reserved. Based in Toronto, Canada.
          </p>
          <p className="text-xs text-muted-foreground flex items-center gap-1">
            Built with <Heart className="h-3 w-3 text-primary fill-primary" /> for Black innovators worldwide
          </p>
        </div>
      </div>
    </footer>
  );
}

export default function Landing() {
  return (
    <div className="min-h-screen bg-background">
      <NavBar />
      <HeroSection />
      <MissionSection />
      <ProgramsSection />
      <HowItWorksSection />
      <ForFoundersSection />
      <TestimonialsSection />
      <FaqSection />
      <CtaBanner />
      <Footer />
    </div>
  );
}


